### ISSUE TITLE
Lizenzinformationen zu CC BY-SA 4.0

### ISSUE THREAD

**Issue by tsandmann** [Nightwalker-87/ct-bot-doku#23]
**Describe the bug**
Bei den folgenden Dateien wurde der Lizenzhinweis zu CC BY-SA 4.0 entfernt, das finde ich nach wie vor nicht okay:

- _tmp_wikis_export/AVRToolchain/AVRToolchain.md
- _tmp_wikis_export/AVRToolchain/AVRToolchainInterna.md
- _tmp_wikis_export/AppletHowto/AppletHowto.md
- _tmp_wikis_export/DokuScriptLanguages/DokuScriptLanguages.md
- _tmp_wikis_export/Eclipse/AntMiniHowto.md
- _tmp_wikis_export/Eclipse/EclipseTipps.md
- _tmp_wikis_export/Eclipse/GITUndEclipse.md
- _tmp_wikis_export/Flash/Flash.md
- _tmp_wikis_export/Funktionen/Bot2Bot.md
- _tmp_wikis_export/Funktionen/BotFs.md
- _tmp_wikis_export/Funktionen/OS.md
- _tmp_wikis_export/Funktionen/Protocol.md
- _tmp_wikis_export/Funktionen/RemoteCall.md
- _tmp_wikis_export/Installationsanleitung.md
- _tmp_wikis_export/InstallationsanleitungR23.md
- _tmp_wikis_export/Localization/Localization.md
- _tmp_wikis_export/Verhalten/NeueVerhalten.md
- _tmp_wikis_export/Verhalten/Verhalten.md
- _tmp_wikis_export/ct-Bot-Software/ct-Bot-Software-Aktuatoren.md
- _tmp_wikis_export/ct-Bot-Software/ct-Bot-Software-Sensoren.md
- _tmp_wikis_export/ct-Bot-Software/ct-Bot-Software.md
- _tmp_wikis_export/ct-Sim/DokuSimulationsArchitektur.md
- _tmp_wikis_export/ct-Sim/SimConfig.md
- _tmp_wikis_export/xx_HW/RaspberryPi.md
- _tmp_wikis_export/xx_HW/ct-Bot-Modifikationen.md
- _tmp_wikis_export/xx_Patches/Patches.md

**To Reproduce**
N/A

**Expected behavior**
Lizenzinformationen wie [hier](https://github.com/tsandmann/ct-bot-doku/tree/69041f7df05e9552c329f992f2fc628117dd1b83/_tmp_trac_wiki_export/) bei den jeweiligen Dateien am Ende vorhanden.

**Desktop (please complete the following information):**
N/A

**Comment by Nightwalker-87** [comment]
Nein, die Lizenzhinweise fehlen _nicht_, bei ungesichteten Inhalten befindet sich lediglich kein Lizenz-Template am Ende der jeweiligen Seite (das im Übrigen auch gar nicht vorgeschrieben ist). Dies ist meinerseits aus obigem Grund auch so vorgesehen. Da im Lizenz-Header der alten Seiten jedoch explizit auf die Lizenz verwiesen wird, ist die Lizenzierung eindeutig gekennzeichnet. Daher ist meinerseits hier keine Änderung beabsichtigt.
