### ISSUE TITLE
Doku zu MMC_VM_AVAILABLE in ct-Bot.h

### ISSUE THREAD

**Issue by Nightwalker-87** [Nightwalker-87/ct-bot-doku#4]
Bei der Überarbeitung des Wikis bin ich in Doku zu ct-bot.h auf folgende Funktion gestoßen:

> `MMC_VM_AVAILABLE` (*deprecated*): Aktiviert das Virtual Memory Management mit MMC/SD-Karte oder PC-Emulation. Damit kümmert sich der Bot selbst um das Ein- und Auslagern von Speicherseiten, die auf der MMC liegen und stellt somit einen einfach zu benutzenden und großen Speicherraum zur Verfügung. Ebenso wird das Lesen und Schreiben von Dateien auf der MMC durch Caching optimiert. Diese Funktion benötigt allerdings relativ viel RAM für den Cache und Flash-Speicher. Daher wird als Hardware mindestens ein ATMega644(P) empfohlen. Beim simulierten Bot schaltet diese Option die emulierte MMC ein, welche die Daten für die Verhalten, die der Bot auf der MMC speichert, völlig transparent in eine Datei umleitet.

Ist diese Option bzw ihre Implementierung überhaupt noch im Code? Wenn nein, wann ist diese entfernt worden?

**Comment by tsandmann** [comment]
Nein, gibt es nicht mehr. Wurde mit Commit b1043b54 entfernt.

**Comment by Nightwalker-87** [comment]
Alles klar, danke!
