### ISSUE TITLE
Fotos vom Interface-Board für die BeagleBoard Erweiterung?

### ISSUE THREAD

**Issue by Nightwalker-87** [Nightwalker-87/ct-bot-doku#7]
Gibt es irgendwo noch ein oder mehrere Fotos vom BB-Interface-Board die in den entsprechenden Artikel eingebunden werden könnten?

**Comment by tsandmann** [comment]
Hm ne, ich glaube nicht.

**Comment by Nightwalker-87** [comment]
Hm, schade - dafür gibt es aber eine Bilderflut von Terminal-Screenshots, für jede einzelne Eingabe bei der Installation und Konfiguration des Boards. Ich binde diese jetzt zwar erstmal ein für einen Review, aber ich finde das schon ziemlich bescheuert... Die Eingabe in Markdown wäre deutlich leserlicher und übersichtlicher. :-/

**Comment by tsandmann** [comment]
Lass sie doch einfach weg, dürfte eh nicht mehr aktuell sein.

**Comment by Nightwalker-87** [comment]
ja, aber wir wollten doch auch alten Content auch noch archivieren ;-)
Die Bilder sind jetzt erstmal drin - kann man nachher noch ersetzen, Hauptsache der Artikel hat erstmal seine Überarbeitung und eine sinnvolle Struktur.
